# Generated by Django 4.2.4 on 2023-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('two wheelers', 'Two wheelers'), ('three wheelers', 'Three wheelers'), ('four wheelers', 'Four wheelers')], default=None, max_length=20),
        ),
    ]
